#**Análise exploratória da base final**

1.   Teste de distribuição
2.   Entropia


Para esse notebook usarei a base final que contém as colunas abaixo:

**Dicionário das variáveis:**

| Variável                                                                 | Abreviação |
|--------------------------------------------------------------------------|------------|
| Consumo anual de energia elétrica residencial                            | CAER       |
| Consumo anual de energia elétrica comercial                              | CAEC       |
| Rendimento do trabalho formal                                            | RTF        |
| Indicador Riqueza                                                        | IndRiq     |
| Taxas de mortalidade infantil                                            | TMI        |
| Taxas de mortalidade perinatal                                           | TMP        |
| Taxas de mortalidade 15 a 39 anos                                        | TM1539     |
| Taxas de mortalidade 60 a 69 anos                                        | TM6069     |
| Indicador Longevidade                                                    | IndLong    |
| Taxa de atendimento escolar na faixa etária de 0 a 3 anos                | TAE03      |
| Proporção média de alunos do 5º ano com proficiência em Língua Portuguesa e Matemática | Prof5ano   |
| Proporção média de alunos do 9º ano com proficiência em Língua Portuguesa e Matemática | Prof9ano   |
| Taxas de distorção idade-série no Ensino Médio                           | TDISM      |
| Indicador Escolaridade                                                   | IndEsc     |
| Região Geográfica Intermediária                                          | RGInter    |
| Nome Região Geográfica Intermediária                                     | NRGInter   |
| Região Geográfica Imediata                                               | RGIme      |
| Nome Região Geográfica Imediata                                          | NRGIme     |
| Agropecuária                                                             | Agrop      |
| Administração pública                                                    | AdmPub     |
| Serviços (exceto administração pública)                                  | ServExc    |
| Valor adicionado                                                         | ValAdic    |
| Impostos líquido de subsídios                                            | ImpLiq     |
| PIB per capita                                                           | PIBpc      |
| Furto de veículo                                                         | FV         |
| Furto outros                                                             | FO         |
| Homicídio culposo outros                                                 | HC         |
| Homicídio culposo por acidente de trânsito                               | HCA        |
| Latrocínio                                                               | Lat        |
| Lesão corporal culposa outras                                            | LCC        |
| Lesão corporal culposa por acidente de trânsito                          | LCCA       |
| Lesão corporal dolosa                                                    | LCD        |
| Vítimas de homicídio                                                     | VH         |
| Tentativa de homicídio                                                   | TH         |
| Total de estupro                                                         | TE         |
| Total de Roubo                                                           | TR         |
| Indice Criminalidade                                                     | IC         |
| Classificação                                                            | CL         |

# Bibliotecas utilizadas

In [ ]:
import pandas as pd
import geopandas as gpd

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
!pip install --upgrade plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly) (9.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly) (24.2)

In [ ]:
import plotly.figure_factory as ff
import numpy as np

In [ ]:
from scipy.stats import entropy, zscore, shapiro
from sklearn.preprocessing import MinMaxScaler

# Importação das bases

In [ ]:
!git clone "https://github.com/MurilloYumoto/Analise-Criminal-no-Brasil"

Cloning into 'Analise-Criminal-no-Brasil'...
remote: Enumerating objects: 272, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 272 (delta 40), reused 73 (delta 30), pack-reused 185 (from 1)
Receiving objects: 100% (272/272), 81.38 MiB | 22.00 MiB/s, done.
Resolving deltas: 100% (109/109), done.
Updating files: 100% (131/131), done.

In [ ]:
df_2014 = gpd.read_file('/content/Analise-Criminal-no-Brasil/Base_final/2014/2014.shp')
df_2016 = gpd.read_file('/content/Analise-Criminal-no-Brasil/Base_final/2016/2016.shp')
df_2018 = gpd.read_file('/content/Analise-Criminal-no-Brasil/Base_final/2018/2018.shp')
df_2020 = gpd.read_file('/content/Analise-Criminal-no-Brasil/Base_final/2020/2020.shp')

# Análise descritiva

A ideia nessa seção não foi realizar uma análise descritiva muito extensa e exautisva, e sim uma análise mais direcionada para o que os dados indicaram nas primeiras análises.

Nesse sentido, realizei primeiramente uma análise das distribuições das colunas de interesse. Para isso, plotei os histogramas de cada variável. No entanto, o histograma clássico não possibilitou uma boa vizualização dos dados, haja vista que eles possuiam uma distribuição assimétrica (se considerar os dados de municípios grandes e homogenêa se desconsiderá-los) pela grande diferença entre os casos nos menores mnicípios e nos maiores. Para lidar com isso, testei algumas alternativas para melhorar a vizualização e entender melhor o comportamento dos dados.

Após isso, realizei o teste Shapiro-Wilk para confrmar o que já foi possível perceber pelos histogramas - que os dados não seguiam a distribuição normal.

Seguindo a análise, calculei a Entropia de Shannon

In [ ]:
df_2014['NRGInter'].unique()

array(['Sorocaba', 'São Paulo', 'São José dos Campos', 'Marília',
       'Campinas', 'Bauru', 'Presidente Prudente', 'Araraquara',
       'Araçatuba', 'Ribeirão Preto', 'São José do Rio Preto'],
      dtype=object)

In [ ]:
df_2014

,cod_ibge,Municipio,Area_Km2,Ano,IPDM,CAER,CAEC,RTF,IndRiq,TMI,...,LCC2014,LCCA2014,LCD2014,VH2014,TH2014,TE2014,TR2014,IC2014,CL2014,geometry
0,3509908,Cananeia,1237.357,2014,0.480,2.562923,8.001560,644.220358,0.339,7.604563,...,0,13,93,1,1,12,9,0.367274,Baixo,"POLYGON ((-47.83033 -24.75638, -47.83013 -24.7..."
1,3520426,Ilha Comprida,196.567,2014,0.534,3.706455,8.709898,815.521197,0.501,10.856454,...,0,68,121,1,8,10,50,1.000000,Muito Alto,"POLYGON ((-47.4366 -24.67434, -47.43638 -24.67..."
2,3505401,Barra do Turvo,1007.670,2014,0.335,1.498860,3.513185,572.414524,0.201,16.949153,...,0,16,34,4,3,1,50,0.273911,Baixo,"POLYGON ((-48.44457 -24.65134, -48.44418 -24.6..."
3,3509254,Cajati,454.436,2014,0.443,1.778662,6.070423,1237.874551,0.337,14.363885,...,0,65,127,3,5,20,72,0.252907,Baixo,"POLYGON ((-48.1556 -24.64078, -48.15505 -24.64..."
4,3524600,Jacupiranga,704.189,2014,0.479,1.803224,5.102513,900.044501,0.286,12.482663,...,2,52,101,1,1,7,31,0.273059,Baixo,"POLYGON ((-48.00104 -24.5716, -48.0004 -24.572..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,3530003,Mira Estrela,216.825,2014,0.544,1.742547,5.400891,683.838622,0.261,10.526316,...,0,3,9,0,0,1,0,0.117943,Muito Baixo,"POLYGON ((-50.10224 -19.87441, -50.09732 -19.8..."
636,3520707,Indiapora,279.606,2014,0.549,1.910248,6.378619,826.516748,0.286,13.468013,...,1,17,25,0,0,2,1,0.255380,Baixo,"POLYGON ((-50.20045 -19.86626, -50.19701 -19.8..."
637,3529658,Mesopolis,148.636,2014,0.524,1.701754,7.133663,504.006583,0.269,17.964072,...,0,3,4,0,0,0,1,0.072484,Muito Baixo,"POLYGON ((-50.61347 -19.86537, -50.61346 -19.8..."
638,3534757,Ouroeste,288.648,2014,0.553,2.128705,9.940984,1860.745415,0.391,9.592326,...,6,26,53,1,2,4,9,0.250321,Baixo,"POLYGON ((-50.44955 -19.78895, -50.44771 -19.7..."
639,3540408,Populina,315.938,2014,0.498,1.914729,7.618852,715.405286,0.293,20.172911,...,1,8,17,0,1,1,0,0.189046,Muito Baixo,"POLYGON ((-50.46472 -19.78053, -50.46144 -19.7..."

In [ ]:
df_2014.describe()

,cod_ibge,Area_Km2,Ano,IPDM,CAER,CAEC,RTF,IndRiq,TMI,TMP,...,HCA2014,Lat2014,LCC2014,LCCA2014,LCD2014,VH2014,TH2014,TE2014,TR2014,IC2014
count,6.400000e+02,640.000000,640.0,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,...,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000
mean,3.528710e+06,385.335630,2014.0,0.505297,2.207451,14.671697,1230.826570,0.351492,11.570542,14.031099,...,6.867188,0.584375,6.157813,207.800000,237.582812,7.042187,8.515625,15.579688,485.829687,0.243008
std,1.668869e+04,320.818997,0.0,0.052975,0.495214,13.517291,835.544022,0.075797,5.376269,5.777779,...,23.779494,5.917461,44.377860,1066.255969,1330.665102,49.407346,54.248859,93.498646,6388.912788,0.091256
min,3.500105e+06,3.612000,2014.0,0.335000,1.150799,1.723647,302.512240,0.154000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.514576e+06,157.744500,2014.0,0.472000,1.933033,7.240813,761.259029,0.295750,8.356546,10.565541,...,1.000000,0.000000,0.000000,9.000000,24.000000,0.000000,0.000000,2.000000,2.000000,0.185057
50%,3.528754e+06,280.771000,2014.0,0.507500,2.152456,10.989124,1025.295278,0.347000,11.256558,13.768903,...,3.000000,0.000000,0.000000,26.500000,64.500000,1.000000,2.000000,4.000000,9.000000,0.235973
75%,3.543130e+06,511.861750,2014.0,0.543000,2.395386,16.753375,1463.307156,0.402000,14.338241,17.221969,...,7.000000,0.000000,2.000000,136.250000,195.250000,3.000000,5.000000,12.000000,56.250000,0.291455
max,3.557303e+06,1978.795000,2014.0,0.681000,7.542890,138.088608,9781.822156,0.653000,45.454545,38.567493,...,538.000000,147.000000,1062.000000,25040.000000,32652.000000,1198.000000,1328.000000,2292.000000,160210.000000,1.000000

## Distribuição dos dados

### Histograma normal

In [ ]:
#@title Função
def histograma(df, coluna, bins=40):
    fig = go.Figure()
    fig.add_trace(go.Histogram(x=df[coluna], nbinsx=bins, name=coluna))

    fig.update_layout(
        title=f"Histograma da coluna {coluna}",
        xaxis_title=coluna,
        yaxis_title="Frequência",
        bargap=0.2
    )

    fig.show()

In [ ]:
histograma(df_2014, 'FO2014')

### Histograma por faixa populacionais

In [ ]:
bins = [0, 5000, 50000, 500000, float('inf')]
labels = ['Pequeno', 'Médio', 'Grande', 'Muito Grande']

df_2014['Categoria População'] = pd.cut(df_2014['populacao'], bins=bins, labels=labels)

contagem_categorias = df_2014['Categoria População'].value_counts()

print(contagem_categorias)

Categoria População
Médio           357
Pequeno         154
Grande          120
Muito Grande      9
Name: count, dtype: int64

In [ ]:
#@title Função
def histograma_faixas_pop(df, coluna, populacao_coluna):

    bins = [0, 5000, 50000, 500000, float('inf')]
    #bins = [0, 50000, 200000, 1000000, float('inf')]  menos informativa da distribuição real
    labels = ['Pequeno', 'Médio', 'Grande', 'Muito Grande']
    df['faixa_populacional'] = pd.cut(df[populacao_coluna], bins=bins, labels=labels)


    fig = go.Figure()
    for faixa in labels:
        faixa_df = df[df['faixa_populacional'] == faixa]
        fig.add_trace(go.Histogram(
            x=faixa_df[coluna],
            name=f'Faixa: {faixa}',
            nbinsx=20
        ))

    fig.update_layout(
        title=f'Histograma de {coluna} (Agrupado por Faixas Populacionais)',
        xaxis_title=coluna,
        yaxis_title='Frequência',
        bargap=0.2,
        #xaxis_type="log",
        barmode='overlay'
    )

    fig.show()

In [ ]:
histograma_faixas_pop(df_2014, coluna='FO2014', populacao_coluna='populacao')

In [ ]:
histograma_faixas_pop(df_2014, coluna='IC2014', populacao_coluna='populacao')

### Histograma com dados normalizados por z-score

In [ ]:
#@title Função
def histograma_zscore(df, coluna):
    df['zscore'] = zscore(df[coluna])

    fig = go.Figure()
    fig.add_trace(go.Histogram(
        x=df['zscore'],
        name=f'Z-score de {coluna}',
        nbinsx=20
    ))

    fig.update_layout(
        title=f'Histograma de {coluna} (Normalizado por Z-Score)',
        xaxis_title=f'{coluna} normalizada',
        yaxis_title='Frequência',
        bargap=0.2
    )

    fig.show()

In [ ]:
histograma_zscore(df_2014, coluna='FO2014')

### Histograma com dados normalizados por min-max

In [ ]:
#@title Função
def histograma_minmax(df, coluna):
    scaler = MinMaxScaler()
    df['minmax'] = scaler.fit_transform(df[[coluna]])

    fig = go.Figure()
    fig.add_trace(go.Histogram(
        x=df['minmax'],
        name=f'Min-Max de {coluna}',
        nbinsx=20
    ))

    fig.update_layout(
        title=f'Histograma de {coluna} (Normalizado por Min-Max)',
        xaxis_title=f'{coluna} normalizada',
        yaxis_title='Frequência',
        bargap=0.2
    )

    fig.show()

In [ ]:
 histograma_minmax(df_2014, coluna='FO2014')

### Histograma com dados agrupados por regiões intermediárias

In [ ]:
#@title Função
def histograma_reg_int(df, coluna):
    df_agrupado = df.groupby('NRGInter')

    fig = go.Figure()

    for name, group in df_agrupado:
        fig.add_trace(go.Histogram(x=group[coluna], name=name, nbinsx=20))
    fig.update_layout(
        title=f'Histograma da coluna {coluna} (Agrupado por Região Intermediária)',
        xaxis_title=coluna,
        yaxis_title='Frequência',
        bargap=0.2,
        barmode='overlay'
    )

    fig.show()

In [ ]:
histograma_reg_int(df_2014, 'FV2014')

In [ ]:
histograma_reg_int(df_2014, 'FO2014')

### Histograma com transformação log

In [ ]:
#@title Função
def histograma_log_transform(df, coluna, base_log=np.e):

    if (df[coluna] <= 0).any():
        print(f"A coluna '{coluna}' contém valores <= 0. Esses valores serão ignorados.")
    dados_transformados = np.log(df[coluna][df[coluna] > 0]) / np.log(base_log)

    fig = go.Figure()
    fig.add_trace(go.Histogram(
        x=dados_transformados,
        name=f'Log-{base_log} de {coluna}',
        nbinsx=20
    ))

    fig.update_layout(
        title=f'Histograma da Coluna {coluna} (Transformação Logarítmica - Base {base_log})',
        xaxis_title=f'Log-{base_log}({coluna})',
        yaxis_title='Frequência',
        bargap=0.2
    )

    fig.show()

In [ ]:
histograma_log_transform(df_2014, 'FO2014', base_log=10)

In [ ]:
histograma_log_transform(df_2014, 'FO2014', base_log=np.e)

### Teste Shapiro Wilk

In [ ]:
def shapiro_test(df, coluna, nivel_significancia=0.05):

    estatistica, p_valor = shapiro(df[coluna].dropna())

    return {
        "Variável": coluna,
        "Estatística": estatistica,
        "P-Valor": p_valor,
        "Normal": p_valor > nivel_significancia,
    }

In [ ]:
#@title Resultados com São Paulo
resultados = {}
for coluna in df_2014.select_dtypes(include=['number']).columns:
    resultados[coluna] = shapiro_test(df_2014, coluna)


for coluna, resultado in resultados.items():
    print(f"Coluna: {coluna}")
    print(f"  Estatística: {resultado['Estatística']:.4f}")
    print(f"  P-Valor: {resultado['P-Valor']:.4f}")
    print(f"  Normal: {'Sim' if resultado['Normal'] else 'Não'}")
    print()

Coluna: cod_ibge
  Estatística: 0.9538
  P-Valor: 0.0000
  Normal: Não

Coluna: Area_Km2
  Estatística: 0.8297
  P-Valor: 0.0000
  Normal: Não

Coluna: Ano
  Estatística: 1.0000
  P-Valor: 1.0000
  Normal: Sim

Coluna: IPDM
  Estatística: 0.9925
  P-Valor: 0.0027
  Normal: Não

Coluna: CAER
  Estatística: 0.7898
  P-Valor: 0.0000
  Normal: Não

Coluna: CAEC
  Estatística: 0.6374
  P-Valor: 0.0000
  Normal: Não

Coluna: RTF
  Estatística: 0.6582
  P-Valor: 0.0000
  Normal: Não

Coluna: IndRiq
  Estatística: 0.9882
  P-Valor: 0.0000
  Normal: Não

Coluna: TMI
  Estatística: 0.9602
  P-Valor: 0.0000
  Normal: Não

Coluna: TMP
  Estatística: 0.9763
  P-Valor: 0.0000
  Normal: Não

Coluna: TM1539
  Estatística: 0.9572
  P-Valor: 0.0000
  Normal: Não

Coluna: TM6069
  Estatística: 0.9852
  P-Valor: 0.0000
  Normal: Não

Coluna: IndLong
  Estatística: 0.9917
  P-Valor: 0.0012
  Normal: Não

Coluna: TAE03
  Estatística: 0.9844
  P-Valor: 0.0000
  Normal: Não

Coluna: Prof5ano
  Estatística: 0.9969
  P-Valor: 0.2523
  Normal: Sim

Coluna: Prof9ano
  Estatística: 0.9709
  P-Valor: 0.0000
  Normal: Não

Coluna: TDISM
  Estatística: 0.9531
  P-Valor: 0.0000
  Normal: Não

Coluna: IndEsc
  Estatística: 0.9953
  P-Valor: 0.0492
  Normal: Não

Coluna: RGInter
  Estatística: 0.9369
  P-Valor: 0.0000
  Normal: Não

Coluna: RGIme
  Estatística: 0.9627
  P-Valor: 0.0000
  Normal: Não

Coluna: populacao
  Estatística: 0.0783
  P-Valor: 0.0000
  Normal: Não

Coluna: homens
  Estatística: 0.0804
  P-Valor: 0.0000
  Normal: Não

Coluna: mulheres
  Estatística: 0.0765
  P-Valor: 0.0000
  Normal: Não

Coluna: razao_sexo
  Estatística: 0.6502
  P-Valor: 0.0000
  Normal: Não

Coluna: id_media
  Estatística: 0.9955
  P-Valor: 0.0634
  Normal: Sim

Coluna: dens_demog
  Estatística: 0.2385
  P-Valor: 0.0000
  Normal: Não

Coluna: Agrop
  Estatística: 0.5955
  P-Valor: 0.0000
  Normal: Não

Coluna: Indústria
  Estatística: 0.1350
  P-Valor: 0.0000
  Normal: Não

Coluna: AdmPub
  Estatística: 0.0843
  P-Valor: 0.0000
  Normal: Não

Coluna: ServExc
  Estatística: 0.0548
  P-Valor: 0.0000
  Normal: Não

Coluna: ValAdic
  Estatística: 0.0661
  P-Valor: 0.0000
  Normal: Não

Coluna: ImpLiq
  Estatística: 0.0641
  P-Valor: 0.0000
  Normal: Não

Coluna: PIB
  Estatística: 0.0656
  P-Valor: 0.0000
  Normal: Não

Coluna: PIBpc
  Estatística: 0.4963
  P-Valor: 0.0000
  Normal: Não

Coluna: FV2014
  Estatística: 0.0549
  P-Valor: 0.0000
  Normal: Não

Coluna: FO2014
  Estatística: 0.0547
  P-Valor: 0.0000
  Normal: Não

Coluna: HC2014
  Estatística: 0.1240
  P-Valor: 0.0000
  Normal: Não

Coluna: HCA2014
  Estatística: 0.1925
  P-Valor: 0.0000
  Normal: Não

Coluna: Lat2014
  Estatística: 0.0583
  P-Valor: 0.0000
  Normal: Não

Coluna: LCC2014
  Estatística: 0.0933
  P-Valor: 0.0000
  Normal: Não

Coluna: LCCA2014
  Estatística: 0.1348
  P-Valor: 0.0000
  Normal: Não

Coluna: LCD2014
  Estatística: 0.0953
  P-Valor: 0.0000
  Normal: Não

Coluna: VH2014
  Estatística: 0.0886
  P-Valor: 0.0000
  Normal: Não

Coluna: TH2014
  Estatística: 0.0930
  P-Valor: 0.0000
  Normal: Não

Coluna: TE2014
  Estatística: 0.0906
  P-Valor: 0.0000
  Normal: Não

Coluna: TR2014
  Estatística: 0.0405
  P-Valor: 0.0000
  Normal: Não

Coluna: IC2014
  Estatística: 0.9365
  P-Valor: 0.0000
  Normal: Não

Coluna: zscore
  Estatística: 0.0547
  P-Valor: 0.0000
  Normal: Não

Coluna: minmax
  Estatística: 0.0547
  P-Valor: 0.0000
  Normal: Não

/usr/local/lib/python3.10/dist-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

scipy.stats.shapiro: Input data has range zero. The results may not be accurate.

In [ ]:
#@title Resultados sem São Paulo
df_2014 = df_2014[df_2014['Municipio'] != 'Sao Paulo']

resultados = {}
for coluna in df_2014.select_dtypes(include=['number']).columns:
    resultados[coluna] = shapiro_test(df_2014, coluna)

for coluna, resultado in resultados.items():
    print(f"Coluna: {coluna}")
    print(f"  Estatística: {resultado['Estatística']:.4f}")
    print(f"  P-Valor: {resultado['P-Valor']:.4f}")
    print(f"  Normal: {'Sim' if resultado['Normal'] else 'Não'}")
    print()

/usr/local/lib/python3.10/dist-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

scipy.stats.shapiro: Input data has range zero. The results may not be accurate.

Coluna: cod_ibge
  Estatística: 0.9540
  P-Valor: 0.0000
  Normal: Não

Coluna: Area_Km2
  Estatística: 0.8314
  P-Valor: 0.0000
  Normal: Não

Coluna: Ano
  Estatística: 1.0000
  P-Valor: 1.0000
  Normal: Sim

Coluna: IPDM
  Estatística: 0.9926
  P-Valor: 0.0030
  Normal: Não

Coluna: CAER
  Estatística: 0.7893
  P-Valor: 0.0000
  Normal: Não

Coluna: CAEC
  Estatística: 0.6350
  P-Valor: 0.0000
  Normal: Não

Coluna: RTF
  Estatística: 0.6557
  P-Valor: 0.0000
  Normal: Não

Coluna: IndRiq
  Estatística: 0.9882
  P-Valor: 0.0001
  Normal: Não

Coluna: TMI
  Estatística: 0.9603
  P-Valor: 0.0000
  Normal: Não

Coluna: TMP
  Estatística: 0.9765
  P-Valor: 0.0000
  Normal: Não

Coluna: TM1539
  Estatística: 0.9574
  P-Valor: 0.0000
  Normal: Não

Coluna: TM6069
  Estatística: 0.9853
  P-Valor: 0.0000
  Normal: Não

Coluna: IndLong
  Estatística: 0.9917
  P-Valor: 0.0013
  Normal: Não

Coluna: TAE03
  Estatística: 0.9844
  P-Valor: 0.0000
  Normal: Não

Coluna: Prof5ano
  Estatística: 0.9969
  P-Valor: 0.2605
  Normal: Sim

Coluna: Prof9ano
  Estatística: 0.9710
  P-Valor: 0.0000
  Normal: Não

Coluna: TDISM
  Estatística: 0.9527
  P-Valor: 0.0000
  Normal: Não

Coluna: IndEsc
  Estatística: 0.9954
  P-Valor: 0.0541
  Normal: Sim

Coluna: RGInter
  Estatística: 0.9371
  P-Valor: 0.0000
  Normal: Não

Coluna: RGIme
  Estatística: 0.9630
  P-Valor: 0.0000
  Normal: Não

Coluna: populacao
  Estatística: 0.4134
  P-Valor: 0.0000
  Normal: Não

Coluna: homens
  Estatística: 0.4174
  P-Valor: 0.0000
  Normal: Não

Coluna: mulheres
  Estatística: 0.4098
  P-Valor: 0.0000
  Normal: Não

Coluna: razao_sexo
  Estatística: 0.6478
  P-Valor: 0.0000
  Normal: Não

Coluna: id_media
  Estatística: 0.9955
  P-Valor: 0.0636
  Normal: Sim

Coluna: dens_demog
  Estatística: 0.2333
  P-Valor: 0.0000
  Normal: Não

Coluna: Agrop
  Estatística: 0.5956
  P-Valor: 0.0000
  Normal: Não

Coluna: Indústria
  Estatística: 0.3771
  P-Valor: 0.0000
  Normal: Não

Coluna: AdmPub
  Estatística: 0.4122
  P-Valor: 0.0000
  Normal: Não

Coluna: ServExc
  Estatística: 0.2853
  P-Valor: 0.0000
  Normal: Não

Coluna: ValAdic
  Estatística: 0.3360
  P-Valor: 0.0000
  Normal: Não

Coluna: ImpLiq
  Estatística: 0.2708
  P-Valor: 0.0000
  Normal: Não

Coluna: PIB
  Estatística: 0.3253
  P-Valor: 0.0000
  Normal: Não

Coluna: PIBpc
  Estatística: 0.4949
  P-Valor: 0.0000
  Normal: Não

Coluna: FV2014
  Estatística: 0.2821
  P-Valor: 0.0000
  Normal: Não

Coluna: FO2014
  Estatística: 0.3545
  P-Valor: 0.0000
  Normal: Não

Coluna: HC2014
  Estatística: 0.4063
  P-Valor: 0.0000
  Normal: Não

Coluna: HCA2014
  Estatística: 0.5038
  P-Valor: 0.0000
  Normal: Não

Coluna: Lat2014
  Estatística: 0.3343
  P-Valor: 0.0000
  Normal: Não

Coluna: LCC2014
  Estatística: 0.3129
  P-Valor: 0.0000
  Normal: Não

Coluna: LCCA2014
  Estatística: 0.4257
  P-Valor: 0.0000
  Normal: Não

Coluna: LCD2014
  Estatística: 0.4984
  P-Valor: 0.0000
  Normal: Não

Coluna: VH2014
  Estatística: 0.3553
  P-Valor: 0.0000
  Normal: Não

Coluna: TH2014
  Estatística: 0.4600
  P-Valor: 0.0000
  Normal: Não

Coluna: TE2014
  Estatística: 0.4542
  P-Valor: 0.0000
  Normal: Não

Coluna: TR2014
  Estatística: 0.2678
  P-Valor: 0.0000
  Normal: Não

Coluna: IC2014
  Estatística: 0.9364
  P-Valor: 0.0000
  Normal: Não

Coluna: zscore
  Estatística: 0.3545
  P-Valor: 0.0000
  Normal: Não

Coluna: minmax
  Estatística: 0.3545
  P-Valor: 0.0000
  Normal: Não

## Demais partes

## Entropia de Shannon

Os resultados da Entropia de Shannon confirmaram o que havia sido visto nos histogramas: os valores baixos para a entropia indicam que os dados possuem poucavariação, ou seja, estão muito agrupados.

In [ ]:
def calcular_entropia_shannon(df, coluna, bins=None):
    if bins:
        dados = pd.cut(df[coluna], bins=bins, labels=False)
    else:
        dados = df[coluna]

    frequencias = dados.value_counts()
    probabilidades = frequencias / frequencias.sum()

    return entropy(probabilidades, base=2)

In [ ]:
colunas_numericas = df_2014.select_dtypes(include=['number']).columns

entropias = {}
for coluna in colunas_numericas:
    entropias[coluna] = calcular_entropia_shannon(df_2014, coluna, bins=10)

print(pd.DataFrame(entropias.items(), columns=['Variável', 'Entropia']).sort_values(by='Entropia', ascending=False))

      Variável  Entropia
0     cod_ibge  3.319854
19       RGIme  3.218476
18     RGInter  3.179306
24    id_media  2.822393
14    Prof5ano  2.662957
17      IndEsc  2.660276
3         IPDM  2.658330
7       IndRiq  2.646881
13       TAE03  2.642515
11      TM6069  2.613600
9          TMP  2.593868
12     IndLong  2.521819
15    Prof9ano  2.480174
1     Area_Km2  2.341388
10      TM1539  2.224306
8          TMI  2.217181
16       TDISM  2.151811
46      IC2014  1.890869
4         CAER  1.442545
23  razao_sexo  1.373730
6          RTF  1.310562
5         CAEC  1.301028
36      HC2014  0.913554
26       Agrop  0.902203
43      TH2014  0.767460
40    LCCA2014  0.694709
41     LCD2014  0.689282
27   Indústria  0.625562
33       PIBpc  0.606991
44      TE2014  0.597912
20   populacao  0.596873
21      homens  0.596873
22    mulheres  0.594904
28      AdmPub  0.591697
37     HCA2014  0.583136
38     Lat2014  0.570722
30     ValAdic  0.545349
32         PIB  0.527713
42      VH2014  0.478164
45      TR2014  0.470892
34      FV2014  0.454030
39     LCC2014  0.448933
31      ImpLiq  0.448828
29     ServExc  0.409074
35      FO2014  0.403468
47      zscore  0.403468
48      minmax  0.403468
25  dens_demog  0.374991
2          Ano  0.000000

## Análise de outliers

Visando entender melhor os dados, fiz uma análise utilizando o método IQR para verificar a presença de outliers para analisar as distribuições após removê-los.

In [ ]:
#@title Função
def calcular_iqr(df, coluna):
    Q1 = df[coluna].quantile(0.25)
    Q3 = df[coluna].quantile(0.75)
    IQR = Q3 - Q1
    return Q1, Q3, IQR

def identificar_outliers(df, colunas, fator=1.5):
    outliers_por_coluna = {}

    for coluna in colunas:
        Q1, Q3, IQR = calcular_iqr(df, coluna)
        limite_inferior = Q1 - fator * IQR
        limite_superior = Q3 + fator * IQR

        outliers = df[(df[coluna] < limite_inferior) | (df[coluna] > limite_superior)]
        outliers_por_coluna[coluna] = outliers

    indices_outliers_multiplos = set()
    for coluna, outliers in outliers_por_coluna.items():
        indices_outliers_multiplos.update(outliers.index)

    indices_outliers_multiplos = list(indices_outliers_multiplos)

    linhas_com_outliers_multiplos = df.loc[indices_outliers_multiplos]

    print("Linhas com outliers em mais de uma coluna:")
    print(linhas_com_outliers_multiplos)

    df_sem_outliers = df.drop(indices_outliers_multiplos)

    return df_sem_outliers, outliers_por_coluna

In [ ]:
colunas = ['FO2014', 'FV2014', 'LCC2014', 'HC2014', 'HCA2014', 'LCCA2014', 'LCD2014', 'VH2014', 'TH2014', 'TE2014', 'TR2014']
df_sem_outliers, outliers_por_coluna = identificar_outliers(df_2014, colunas)

Linhas com outliers em mais de uma coluna:
     cod_ibge                 Municipio  Area_Km2   Ano   IPDM      CAER  \
0     3509908                  Cananeia  1237.357  2014  0.480  2.562923
519   3502804                 Aracatuba  1167.126  2014  0.549  2.847941
9     3542602                  Registro   722.201  2014  0.498  2.080887
525   3501004               Altinopolis   928.956  2014  0.524  2.164307
527   3506102                 Bebedouro   683.192  2014  0.524  2.617377
..        ...                       ...       ...   ...    ...       ...
487   3511102                 Catanduva   290.596  2014  0.557  2.728358
491   3551702               Sertaozinho   403.089  2014  0.578  2.913910
492   3518206                Guararapes   955.637  2014  0.508  2.486386
496   3547908  Santo Antonio da Alegria   310.338  2014  0.478  1.863244
499   3556305                Valparaiso   857.661  2014  0.495  2.352413

          CAEC          RTF  IndRiq        TMI  ...  TH2014  TE2014  TR2014  \
0     8.001560   644.220358   0.339   7.604563  ...       1      12       9
519  19.004123  1583.592125   0.430   8.580672  ...      46      44     529
9     9.577977  1265.218586   0.363  16.491754  ...       3      30      59
525  14.886926  1089.992750   0.365   5.565863  ...       5       6       7
527  21.421637  1642.610967   0.432  10.837070  ...       4      16     162
..         ...          ...     ...        ...  ...     ...     ...     ...
487  14.792463  1803.651806   0.418  14.914938  ...       7      39     249
491  21.708320  2406.842862   0.468  12.850929  ...      10      29     371
492  14.556189  1215.239067   0.383  16.239316  ...       2      10      47
496   6.545307   632.560625   0.287  10.526316  ...       1       3       5
499  11.456770  1331.001026   0.377   7.812500  ...       3       5      32

       IC2014  CL2014                                           geometry  \
0    0.367274   Baixo  POLYGON ((-47.83033 -24.75638, -47.83013 -24.7...
519  0.306126   Baixo  POLYGON ((-50.86471 -20.83114, -50.86245 -20.8...
9    0.263827   Baixo  POLYGON ((-47.79892 -24.35152, -47.79855 -24.3...
525  0.238338   Baixo  POLYGON ((-47.41112 -20.80896, -47.41092 -20.8...
527  0.326866   Baixo  POLYGON ((-48.45389 -20.78572, -48.45384 -20.7...
..        ...     ...                                                ...
487  0.327278   Baixo  POLYGON ((-48.85954 -21.00596, -48.85948 -21.0...
491  0.226126   Baixo  POLYGON ((-47.98799 -20.99193, -47.98624 -20.9...
492  0.231830   Baixo  POLYGON ((-50.76627 -21.00032, -50.75051 -21.0...
496  0.269659   Baixo  POLYGON ((-47.18148 -20.95356, -47.18108 -20.9...
499  0.267557   Baixo  POLYGON ((-50.79842 -20.96293, -50.79794 -20.9...

     Categoria População  faixa_populacional    zscore    minmax
0                  Médio               Médio -0.084643  0.000818
519               Grande              Grande  0.245320  0.014037
9                 Grande              Grande -0.029409  0.003031
525                Médio               Médio -0.087653  0.000697
527               Grande              Grande  0.035118  0.005616
..                   ...                 ...       ...       ...
487               Grande              Grande  0.057630  0.006518
491               Grande              Grande  0.066268  0.006864
492                Médio               Médio -0.059644  0.001819
496                Médio               Médio -0.094590  0.000419
499                Médio               Médio -0.072078  0.001321

[187 rows x 56 columns]

In [ ]:
histograma(df_sem_outliers, 'FO2014')

In [ ]:
#@title Resultados após remoção de outliers
resultados = {}
for coluna in df_sem_outliers.select_dtypes(include=['number']).columns:
    resultados[coluna] = shapiro_test(df_sem_outliers, coluna)


for coluna, resultado in resultados.items():
    print(f"Coluna: {coluna}")
    print(f"  Estatística: {resultado['Estatística']:.4f}")
    print(f"  P-Valor: {resultado['P-Valor']:.4f}")
    print(f"  Normal: {'Sim' if resultado['Normal'] else 'Não'}")
    print()

Coluna: cod_ibge
  Estatística: 0.9525
  P-Valor: 0.0000
  Normal: Não

Coluna: Area_Km2
  Estatística: 0.7879
  P-Valor: 0.0000
  Normal: Não

Coluna: Ano
  Estatística: 1.0000
  P-Valor: 1.0000
  Normal: Sim

Coluna: IPDM
  Estatística: 0.9941
  P-Valor: 0.0786
  Normal: Sim

Coluna: CAER
  Estatística: 0.8954
  P-Valor: 0.0000
  Normal: Não

Coluna: CAEC
  Estatística: 0.5206
  P-Valor: 0.0000
  Normal: Não

Coluna: RTF
  Estatística: 0.5639
  P-Valor: 0.0000
  Normal: Não

Coluna: IndRiq
  Estatística: 0.9898
  P-Valor: 0.0032
  Normal: Não

Coluna: TMI
  Estatística: 0.9690
  P-Valor: 0.0000
  Normal: Não

Coluna: TMP
  Estatística: 0.9798
  P-Valor: 0.0000
  Normal: Não

Coluna: TM1539
  Estatística: 0.9673
  P-Valor: 0.0000
  Normal: Não

Coluna: TM6069
  Estatística: 0.9902
  P-Valor: 0.0042
  Normal: Não

Coluna: IndLong
  Estatística: 0.9942
  P-Valor: 0.0850
  Normal: Sim

Coluna: TAE03
  Estatística: 0.9835
  P-Valor: 0.0001
  Normal: Não

Coluna: Prof5ano
  Estatística: 0.9951
  P-Valor: 0.1673
  Normal: Sim

Coluna: Prof9ano
  Estatística: 0.9707
  P-Valor: 0.0000
  Normal: Não

Coluna: TDISM
  Estatística: 0.9483
  P-Valor: 0.0000
  Normal: Não

Coluna: IndEsc
  Estatística: 0.9923
  P-Valor: 0.0200
  Normal: Não

Coluna: RGInter
  Estatística: 0.9485
  P-Valor: 0.0000
  Normal: Não

Coluna: RGIme
  Estatística: 0.9718
  P-Valor: 0.0000
  Normal: Não

Coluna: populacao
  Estatística: 0.8086
  P-Valor: 0.0000
  Normal: Não

Coluna: homens
  Estatística: 0.8151
  P-Valor: 0.0000
  Normal: Não

Coluna: mulheres
  Estatística: 0.8029
  P-Valor: 0.0000
  Normal: Não

Coluna: razao_sexo
  Estatística: 0.5694
  P-Valor: 0.0000
  Normal: Não

Coluna: id_media
  Estatística: 0.9956
  P-Valor: 0.2374
  Normal: Sim

Coluna: dens_demog
  Estatística: 0.3941
  P-Valor: 0.0000
  Normal: Não

Coluna: Agrop
  Estatística: 0.6413
  P-Valor: 0.0000
  Normal: Não

Coluna: Indústria
  Estatística: 0.2580
  P-Valor: 0.0000
  Normal: Não

Coluna: AdmPub
  Estatística: 0.7966
  P-Valor: 0.0000
  Normal: Não

Coluna: ServExc
  Estatística: 0.5927
  P-Valor: 0.0000
  Normal: Não

Coluna: ValAdic
  Estatística: 0.4954
  P-Valor: 0.0000
  Normal: Não

Coluna: ImpLiq
  Estatística: 0.4228
  P-Valor: 0.0000
  Normal: Não

Coluna: PIB
  Estatística: 0.5161
  P-Valor: 0.0000
  Normal: Não

Coluna: PIBpc
  Estatística: 0.4172
  P-Valor: 0.0000
  Normal: Não

Coluna: FV2014
  Estatística: 0.6179
  P-Valor: 0.0000
  Normal: Não

Coluna: FO2014
  Estatística: 0.7291
  P-Valor: 0.0000
  Normal: Não

Coluna: HC2014
  Estatística: 1.0000
  P-Valor: 1.0000
  Normal: Sim

Coluna: HCA2014
  Estatística: 0.8402
  P-Valor: 0.0000
  Normal: Não

Coluna: Lat2014
  Estatística: 0.1967
  P-Valor: 0.0000
  Normal: Não

Coluna: LCC2014
  Estatística: 0.6770
  P-Valor: 0.0000
  Normal: Não

Coluna: LCCA2014
  Estatística: 0.6649
  P-Valor: 0.0000
  Normal: Não

Coluna: LCD2014
  Estatística: 0.7940
  P-Valor: 0.0000
  Normal: Não

Coluna: VH2014
  Estatística: 0.7204
  P-Valor: 0.0000
  Normal: Não

Coluna: TH2014
  Estatística: 0.7339
  P-Valor: 0.0000
  Normal: Não

Coluna: TE2014
  Estatística: 0.7978
  P-Valor: 0.0000
  Normal: Não

Coluna: TR2014
  Estatística: 0.6320
  P-Valor: 0.0000
  Normal: Não

Coluna: IC2014
  Estatística: 0.9226
  P-Valor: 0.0000
  Normal: Não

Coluna: zscore
  Estatística: 0.7291
  P-Valor: 0.0000
  Normal: Não

Coluna: minmax
  Estatística: 0.7291
  P-Valor: 0.0000
  Normal: Não

/usr/local/lib/python3.10/dist-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

scipy.stats.shapiro: Input data has range zero. The results may not be accurate.